---
title: "<span class='pref'>GW-DATS</span>Undergraduate Curriculum"
subtitle: <green>Fall Faculty Retreat, 2025</green>
author: "<green>Committee</green>: Angie W., James H., Sarah B., and Sush M." 
fig-cap-location: bottom
callout-icon: false
format: 
    revealjs:
        theme: dark
        slide-number: true
        self-contained: true
        incremental: false
        css: style.css
        navigation-mode: vertical
editor: 
  render-on-save: true
html-math-method: mathml
---


# <green>Current</green> Program 

## Prerequisites 

- (CSCI) Introduction to Programming with Python	
- (MATH) Single-Variable Calculus I / Calculus with Precalculus II
- (MATH) Single-Variable Calculus II
- (MATH) Linear Algebra I
- (STAT) Intro to Statistics

## Core DATS Courses

:::{.columns }

:::{.column  width="48%"}

- (1001)_Data Science for All
- (2101)_Ethical Life in a Digital World
- (2102)_Data Vizualization
- (2103)_Data Mining
- (2104)_Data Warehousing
  

:::

::: {.column width="4%"}
<!-- empty column to create gap -->
:::

:::{.column width="48%"}

- (4001)_Data Capstone
  
:::
:::

No optional courses!


# <red>Proposed</red> Program

## Prerequisites {.smaller}

- (CSCI) Introduction to Programming with Python	
  - <red>CS is NOT doing a good job</red>
- (MATH) Single-Variable Calculus I / Calculus with Precalculus II
- (MATH) Single-Variable Calculus II
- (MATH) Linear Algebra I
  - <red>Students are not using these skills</red>
- (STAT) Intro to Statistics
- <red>(STAT)_Regression Analysis?</red>
- <red>(STAT)_Math Stat?</red>

## Core DATS Courses {.smaller}

:::{.columns }

:::{.column width="40%"}


- (1001)_Data Science for All
  - <green>Brainstorm objectives</green>
- (2101)_Ethical Life in a Digital World
- (2102)_Data Vizualization
- (2103)_Data Mining
  - <green>Brainstorm objectives</green>
- (2104)_Data Warehousing
- <red>?_Open-source programming</red>
  - Python, R, Git, Bash, etc
  - Compare and contrast 1001
:::

:::{.column width="60%"}


- <red>?_(Interpretable) Machine Learning (ML)</red>
  - Mathematical foundations
  - Prereq: Multi-var Calc, DATS 2103
- <red>?_Deep Learning</red>
  - Prereq: Multi-var Calc, ML
- <red>Anything else?</red>
- (4001)_Data Capstone
:::
:::

## The Capstone {.smaller}

- projects are naive and not impactful
- need real, <green>research-focused</green> projects with <green>strong outcomes</green>
- Clearly defined outcomes: Dashboard / publications / <red>?</red>
- Forge more ties with industry
- Rethink instruction
  - Instructors require specialized domain knowledge 
  - allow group projects (max. 4 groups/section)
  - lecture-style weekly interaction may not be the best strategy
- <green>CURE</green>: teach courses based on the CURE model (Course-Based Undergraduate Research Experience)
- <red>Other thoughts?</red>

# Domain Concentrations


## List {.smaller}

:::{.columns}

:::{.column}

- Astronomy and astrophysics ✅
- Physics ✅
- Biology: biodiversity and global change ✅
- Biology: biotechnology ✅
- Data journalism <red>?</red>
- Economics ❌
- Geospatial data science ✅
- Mathematical modeling ✅
- Science, technology and society <red>?<red>

:::

:::{.column}

- Statistics
- Our own concentrations
  - Artificial Intelligence
  - Visualization
  - Machine Learning
  - Data Management / engineering / warehousing
- <red>Anything else?</red>

:::

:::

## How to <green>improve</green>?

- There need to be pre-approved list of major and minors that count
- Persons of contact in other departments that are <green>responsive</green> and <green>friendly</green>

- <red>Thoughts?</red>

# DATS <green>Minor</green>

- When does it start?
- Prerequisites / Requirements?
- Can we grow/hire enough faculty/adjuncts to hold the capacity?


# Resources Needed

- More faculty to teach UG courses
- Gradescope
- Overleaf (exam prep, capstone report, articles, etc)
- Standardize books, assignments for multi-section courses like DATS 1001
- Incentives for course development
- Incentives for writing UG research infrastructure grants (NSF/NIH)
- <red>Anything else?</red>


# Future Objectives

- Acquire resources to help sustain the UG program
- Well-defined research component (CURE)
- More faculty with undergraduate pedagogy in mind
- Infrastructure for students, faculty
- <green>New home</green> for DATS


# Thanks